[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pgvector = { version = "0.3", features = ["sqlx"] }
anyhow = "1.0.80"
face_embed = { path = "../face_embed" }
image = "0.24.9"
sqlx = { version = "0.7.3", features = [ "runtime-tokio", "postgres", "chrono" ] }
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
signal-hook = "0.3.17"
ndarray = "0.15.6"
futures-util = "0.3.30"
glob = "0.3.1"
plotters = "0.3.5"
linfa = "0.7.0"
linfa-tsne = "0.7.0"
linfa-reduction = "0.7.0"
clap = { version = "4.5.2", features = ["derive"] }

[dependencies.nokhwa]
git = "https://github.com/l1npengtul/nokhwa.git"
rev = "ea971242a888987222375189fb78c84fa85e5a4e"
features = [ "input-native" ]
