name: face_embed

services:
  s3:
    container_name: s3
    image: quay.io/minio/minio
    command: ['server', '/data', '--console-address', ':9001']
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 9000:9000
      - 9001:9001

  mb:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672

  db:
    container_name: postgres
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  face:
    container_name: faces
    privileged: true
    image: 8ce9fc5b75d2
    restart: always
    environment:
      - CONN_STR=postgres://postgres:postgres@db:5432
      - ADDRESS=amqp://mb:5672/%2f
      - URL=http://s3:9000
      - ACCESS_KEY=minioadmin
      - SECRET_KEY=minioadmin
    volumes:
      - /dev/video0:/dev/video0
    depends_on:
      - s3
      - mb
      - db
