[package]
name = "face_embed"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
fast_image_resize = "3.0.4"
image = "0.24.8"
ndarray = "0.15.6"
num-traits = "0.2.18"
tract-onnx = "0.21.1"
rand = "0.8.5"
